### Common
spring:
  mail:
    host: 100.100.10.142
    username: itsecurity@inveniacorp.com
    password: inveni@2021
    properties:
      mail:
        smtp:
          auth: true
  data:
    rest:
      base-path: /api
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  port: 8080

logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}) %clr(%-5p) %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
  level:
    root: warn
    com.invenia.excel: debug

batch:
  config:
    runCozy: false
    runKd: false
    runMall: true
    didigoWebUrl: "https://mfg.systemevererp.com/"
    cozyWebUrl: "http://100.100.16.16:9997"
    kdWebUrl: "https://mfg.systemevererp.com/"
    mallWebUrl: "https://admin.didigomall.com:444/"

---
### Development
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/automation?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
convert:
  config:
    chrome-download-path: "W:/Downloads/"
    ie-download-path: "W:/IETemp/"
    backup-path: "C:/excel/backup/"
    template-path: "C:/excel/template/"
    output-path: "C:/excel/output/"
    customer-file-name: "customer.xlsx"
    item-code-file-name: "item.xlsx"
    item-price-file-name: "price.xlsx"
    contract-order-file-name: "contractorder.xlsx"
mail:
  recipients:
    - damu@inveniacorp.com
---
### Product
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/automation?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: dpftiq0308
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
convert:
  config:
    chrome-download-path: "C:/Users/chatServer/Downloads/"
    ie-download-path: "C:/Users/chatServer/Downloads/"
    backup-path: "C:/excel/backup/"
    template-path: "C:/excel/template/"
    output-path: "C:/excel/output/"
    customer-file-name: "customer.xlsx"
    item-code-file-name: "item.xlsx"
    item-price-file-name: "price.xlsx"
    contract-order-file-name: "contractorder.xlsx"
mail:
  recipients:
    - ssu@didigo.com
    - redssmile@didigo.com
  carbon-copies:
    - damu@inveniacorp.com
